import { initTRPC } from "@trpc/server";
import { z } from "zod";

const t = initTRPC.create();
const publicProcedure = t.procedure;

const appRouter = t.router({
  app: t.router({
    hello: publicProcedure.output(z.object({ message: z.string() })).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    protectedHello: publicProcedure.output(z.object({ message: z.string() })).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    demoHello: publicProcedure.output(z.object({ message: z.string() })).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    other: publicProcedure.output(z.object({ message: z.string() })).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
  }),
  users: t.router({
    read: publicProcedure.input(z.object({ id: z.string() })).output(z.object({
      id: z.string(),
      name: z.string(),
      email: z.string().email(),
      emailVerified: z.boolean().optional(),
      image: z.string().nullable(),
      createdAt: z.date(),
      updatedAt: z.date(),
      sessions: z.array(z.object({
        id: z.string(),
        userId: z.string(),
        sessionToken: z.string(),
        expiresAt: z.date(),
      })).optional(),
      accounts: z.array(z.object({
        id: z.string(),
        userId: z.string(),
        providerId: z.string(),
        accessToken: z.string(),
        refreshToken: z.string(),
        idToken: z.string(),
        accessTokenExpiresAt: z.date(),
        refreshTokenExpiresAt: z.date(),
      })).optional(),
    })).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    readAll: publicProcedure.output(z.array(z.object({
      id: z.string(),
      name: z.string(),
      email: z.string().email(),
      emailVerified: z.boolean().optional(),
      image: z.string().nullable(),
      createdAt: z.date(),
      updatedAt: z.date(),
      sessions: z.array(z.object({
        id: z.string(),
        userId: z.string(),
        sessionToken: z.string(),
        expiresAt: z.date(),
      })).optional(),
      accounts: z.array(z.object({
        id: z.string(),
        userId: z.string(),
        providerId: z.string(),
        accessToken: z.string(),
        refreshToken: z.string(),
        idToken: z.string(),
        accessTokenExpiresAt: z.date(),
        refreshTokenExpiresAt: z.date(),
      })).optional(),
    }))).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    create: publicProcedure.input(z.object({
      id: z.string(),
      name: z.string(),
      email: z.string().email(),
      emailVerified: z.boolean().optional(),
      image: z.string().nullable(),
      createdAt: z.date(),
      updatedAt: z.date(),
      sessions: z.array(z.object({
        id: z.string(),
        userId: z.string(),
        sessionToken: z.string(),
        expiresAt: z.date(),
      })).optional(),
      accounts: z.array(z.object({
        id: z.string(),
        userId: z.string(),
        providerId: z.string(),
        accessToken: z.string(),
        refreshToken: z.string(),
        idToken: z.string(),
        accessTokenExpiresAt: z.date(),
        refreshTokenExpiresAt: z.date(),
      })).optional(),
    }).omit({
      id: true,
      createdAt: true,
      updatedAt: true,
      sessions: true,
      accounts: true,
    })).output(z.object({
      id: z.string(),
      name: z.string(),
      email: z.string().email(),
      emailVerified: z.boolean().optional(),
      image: z.string().nullable(),
      createdAt: z.date(),
      updatedAt: z.date(),
      sessions: z.array(z.object({
        id: z.string(),
        userId: z.string(),
        sessionToken: z.string(),
        expiresAt: z.date(),
      })).optional(),
      accounts: z.array(z.object({
        id: z.string(),
        userId: z.string(),
        providerId: z.string(),
        accessToken: z.string(),
        refreshToken: z.string(),
        idToken: z.string(),
        accessTokenExpiresAt: z.date(),
        refreshTokenExpiresAt: z.date(),
      })).optional(),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    update: publicProcedure.input(z.object({
      id: z.string(),
      data: z.object({
        id: z.string(),
        name: z.string(),
        email: z.string().email(),
        emailVerified: z.boolean().optional(),
        image: z.string().nullable(),
        createdAt: z.date(),
        updatedAt: z.date(),
        sessions: z.array(z.object({
          id: z.string(),
          userId: z.string(),
          sessionToken: z.string(),
          expiresAt: z.date(),
        })).optional(),
        accounts: z.array(z.object({
          id: z.string(),
          userId: z.string(),
          providerId: z.string(),
          accessToken: z.string(),
          refreshToken: z.string(),
          idToken: z.string(),
          accessTokenExpiresAt: z.date(),
          refreshTokenExpiresAt: z.date(),
        })).optional(),
      }).omit({
        id: true,
        createdAt: true,
        updatedAt: true,
        sessions: true,
        accounts: true,
      }).partial(),
    })).output(z.object({
      id: z.string(),
      name: z.string(),
      email: z.string().email(),
      emailVerified: z.boolean().optional(),
      image: z.string().nullable(),
      createdAt: z.date(),
      updatedAt: z.date(),
      sessions: z.array(z.object({
        id: z.string(),
        userId: z.string(),
        sessionToken: z.string(),
        expiresAt: z.date(),
      })).optional(),
      accounts: z.array(z.object({
        id: z.string(),
        userId: z.string(),
        providerId: z.string(),
        accessToken: z.string(),
        refreshToken: z.string(),
        idToken: z.string(),
        accessTokenExpiresAt: z.date(),
        refreshTokenExpiresAt: z.date(),
      })).optional(),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    delete: publicProcedure.input(z.object({
      id: z.string(),
    })).output(z.object({
      id: z.string(),
      name: z.string(),
      email: z.string().email(),
      emailVerified: z.boolean().optional(),
      image: z.string().nullable(),
      createdAt: z.date(),
      updatedAt: z.date(),
      sessions: z.array(z.object({
        id: z.string(),
        userId: z.string(),
        sessionToken: z.string(),
        expiresAt: z.date(),
      })).optional(),
      accounts: z.array(z.object({
        id: z.string(),
        userId: z.string(),
        providerId: z.string(),
        accessToken: z.string(),
        refreshToken: z.string(),
        idToken: z.string(),
        accessTokenExpiresAt: z.date(),
        refreshTokenExpiresAt: z.date(),
      })).optional(),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
  })
});
export type AppRouter = typeof appRouter;

